### PR TITLE
Add: POST /diary

### PR DESCRIPTION
**Pull request by myuto7**
- [x] diaries
- [x] diary_equipments
- [x] diary_flavor
- [x] user_diaries
- [x] diary_images

### CODE REVIEW

**Review by m-star18 — APPROVED** [review]
ウホホイ

**Comment by m-star18** [comment]
あれ, なにこれ

**Review by m-star18 — DISMISSED** [review]
ほい

**Comment by m-star18** [comment]
メモ: https://github.com/orgs/community/discussions/58535

**Comment by myuto7** [comment]
https://github.com/youngeek-0410/shisha-log-backend/pull/41/commits/fb4b1664a3576c92cd437c13345b500fcf72ccb2 で #50 の対応も入れた

**Review by m-star18 — DISMISSED** [review]
いいやん、うまやん

**Comment by m-star18** [comment]
なんやねん！〜

**Comment by myuto7** [comment]
んだこれ

**Pull request merged**
